[workspace]
authors = ["Zoltan Gutierrez <zoliad.17@gmail.com>"]
channels = ["conda-forge"]
name = "analytics"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
app = "python app.py"
start = "python app.py"
flask = "python -m flask --app app run --port 5001"
flask-dev = "python -m flask --app app run --port 5001 --debug"

[dependencies]
python = "3.13.*"
uv = ">=0.9.13,<0.10"
pandas = ">=2.3.3,<3"
openpyxl = ">=3.1.5,<4"
requests = ">=2.32.5,<3"
