[workspace]
authors = ["Zoltan Gutierrez <zoliad.17@gmail.com>"]
channels = ["conda-forge"]
name = "analytics"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
app = "python app.py"
start = "python app.py"

[dependencies]
python = "3.13.*"
uv = ">=0.9.13,<0.10"
